"""New Migration

Revision ID: 3054d4d49749
Revises: 69b980250a8f
Create Date: 2022-05-29 02:37:21.043817

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3054d4d49749'
down_revision = '69b980250a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
