"""New Migration

Revision ID: 38d83e2ff032
Revises:
Create Date: 2022-05-25 21:46:42.144864

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "38d83e2ff032"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
