"""modify relationship

Revision ID: 4482423e29d4
Revises: bdc73af68c56
Create Date: 2022-05-29 14:36:32.526484

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4482423e29d4'
down_revision = 'bdc73af68c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
