"""empty message

Revision ID: 54cf40d0ed4e
Revises: eea17f32ac25
Create Date: 2022-05-29 15:58:28.844615

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '54cf40d0ed4e'
down_revision = 'eea17f32ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
