"""New Migration

Revision ID: 7ba6dc689081
Revises: 4482423e29d4
Create Date: 2022-05-29 14:58:22.107513

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ba6dc689081'
down_revision = '4482423e29d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
