"""empty message

Revision ID: bdc73af68c56
Revises: f69cedad6c7c
Create Date: 2022-05-29 14:36:01.657997

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bdc73af68c56'
down_revision = 'f69cedad6c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
