"""Add comment data model

Revision ID: f69cedad6c7c
Revises: 3054d4d49749
Create Date: 2022-05-29 13:53:55.816678

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f69cedad6c7c'
down_revision = '3054d4d49749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('text', sa.String(), nullable=True))
    op.add_column('comment', sa.Column('timestamp',
                                       sa.DateTime(),
                                       nullable=True))
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'timestamp')
    op.drop_column('comment', 'text')
    # ### end Alembic commands ###
